### ISSUE TITLE
A freshly created TRenderImage contains garbage

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#1]
Hi

If you just create a new TRenderImage it contains "garbage". Maybe add a convenience method like pixmap's "ClearPixel(0)".

Or am I required to
```BlitzMax
Local gc:TGraphics = Graphics(800, 600)
Local rt:TRenderImage = CreateRenderImage(gc, 800, 600)
SetRenderImage(rt)
Cls
SetRenderImage(Null)
```

also: shouldn't we consider changing `CreateRenderImage()` to be `CreateRenderImage(w,h, graphicscontext=null)`? And if no GC was provided, use the current one?

Edit: or if "flags" are considered later on: stay even more "compatible" with Brl's Image: `CreateRenderImage(w:int, h:int, flags:int=0, gc:TGraphics=null)`

Or do I miss something there?

**Comment by davecamp** [comment]
Hey,

Thanks for testing the initial commit.

I agree with you about the render image containing garbage - this is normal and as you suggest should really be cleared on initialisation.

The DirectX render images need some internal parameters from the TGraphics instance. This is the only way I know to get that instance. There is the GetGraphicsDriver function but that doesn't give me access to a TGraphics instance  - unless there is a method/function that I've missed?

**Comment by GWRon** [comment]
Ahh my fault.

Maybe keep that `g:TGraphics` for now and once you modify modules (which you seem to need anyway) you could expose `_graphics:TGraphics` from **Brl.Graphics** - and make it that way available for the r2t-code.

Another approach (temporary) is to _allow_ null-TGraphics-params but enforce a "SetRenderImageGraphics(g)" which sets a kind of "global".
But hmm, might be a too "dirty" solution.

**Comment by davecamp** [comment]
I think the best/cleanest approach is, as you suggested, with brl.graphics and writing a function such as 

```
GetGraphics:TGraphics()
```

to return the current graphics context.

**Comment by davecamp** [comment]
Fixed 'garbage in image upon creation' with commit 53bcb6be134db28d8a3dfce2089b114a607d381c
