### ISSUE TITLE
Latest DX9 changes

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#10]
Your d3d9graphics.bmx seems to be based on an older /vanilla variant.

brl had already updated it - and I incorporated the changes to maxmods in the past.

So maybe you want to merge your changes:
https://raw.githubusercontent.com/maxmods/brl.mod/master/dxgraphics.mod/d3d9graphics.bmx

**Comment by davecamp** [comment]
Thank you for the link.
Updated.
