### ISSUE TITLE
Imageflags for TRenderImage

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#14]
Is there a way to set a "TImage.flag" for Renderimages?

Especially thinking of removing the "FILTEREDIMAGE" flag (so I can render to a 320x200 screen and then draw it as 640x400 without antialiasing).

**Comment by davecamp** [comment]
Hiya,

I've added an extra parameter to the CreateRenderImage function. It will default to True to use image filtering. Use false for no filtering.

Hope this helps out.
