### ISSUE TITLE
SetViewport within Render2Texture leads to black rect

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#15]
Instead of rendering a shiny blue rectangle in the created image below, the code results in a black window here.

```BlitzMax
SuperStrict

Framework brl.glmax2d
Import brl.standardio
Import "Render2Texture/renderimage.bmx"

global g:TGraphics = Graphics(640, 400, 0)
global renderImage:TRenderImage = CreateRenderImage(g, 320, 200)

While Not KeyDown(key_escape)
	cls

	SetRenderImage(renderImage)
		cls
		Local vpX:Int, vpY:Int, vpH:Int, vpW:Int
		GetViewport(vpX, vpY, vpW, vpH)
		'print "vpX="+vpX+"  vpY="+vpY+"  vpH="+vpH+"  vpW="+vpW
		SetViewport(70, 0, 184, 190)
		SetColor 0,0,250
		DrawRect(70,0,184,190)
		SetColor 255,255,255
		SetViewport(vpX, vpY, vpW, vpH)
	SetRenderImage(Null)

	if renderImage
		SetScale 2,2
		DrawImage(renderImage,0,0)
		SetScale 1,1
	endif

	Flip 1
Wend
```

![](http://i.imgur.com/cFBTGo6.png)

When commenting out the `SetViewport(70, 0, 184, 190)` you have some kind of flickering (think matrix between "normal canvas" and "render image" is borked then.

**Comment by davecamp** [comment]
Hiya,
The problem stems from Max2D using the Max2D graphics height in a calculation within the SetViewport command. Max2D doesn't know about the new, different sized render image of 320 x 200, so when using SetViewport it is doing calculations using the Max2D graphics height of 400 hence the error.

I guess a fix for this would be to do the same by putting a SetViewport method in the renderimage context.

You should be able to set the viewport correctly now by using

    Local renderimage:TRenderImage = CreateRenderImage(320, 200)
    renderimage.SetViewport(0, 0, 320, 200)

The values are not persistant as in traditional OO methodologies, so will need to set each time you want to use it.
To use your own example above would be...
    
    SuperStrict
    
    Framework brl.glmax2d
    Import brl.standardio
    Import "Render2Texture/renderimage.bmx"
    
    Global g:TGraphics = Graphics(640, 400, 0)
    Global renderImage:TRenderImage = CreateRenderImage(g, 320, 200)
    
    While Not KeyDown(key_escape)
    	Cls
    
    	SetRenderImage(renderImage)
    		Cls
    		Local vpX:Int, vpY:Int, vpH:Int, vpW:Int
    		GetViewport(vpX, vpY, vpW, vpH)
    		'print "vpX="+vpX+"  vpY="+vpY+"  vpH="+vpH+"  vpW="+vpW
    		renderImage.SetViewport(70, 0, 184, 190)
    		SetColor 0,0,250
    		DrawRect(70,0,184,190)
    		SetColor 255,255,255
    		SetViewport(vpX, vpY, vpW, vpH)
    	SetRenderImage(Null)
    
    	If renderImage
    		SetScale 2,2
    		DrawImage(renderImage,0,0)
    		SetScale 1,1
    	EndIf
    
    	Flip 1
    Wend

**Comment by GWRon** [comment]
So another "solution" was if you somehow were able to override "SetViewport" with something handling the rendertexture.
_or_
Being able to override the GraphicsHeight() function with something allowing for a "custom set height". So something in the likes of

``` BlitzMax
global _customGraphicsHeight:int = -1
Function GraphicsHeight:int()
  if _customGraphicsHeight <> -1 then return _customGraphicsHeight
  return ...Original height
End Function
```
So you are able to modify the returned value "temporarily" (but needs adjustments to brl-modules then).

**Comment by GWRon** [comment]
Maybe a better approach would be to rewrite Max2D core to have some kind of "canvasSettings"-object which either is configuring the application canvas - or something like the rendertarget.
The canvasSetting would contain width, height, transformation matrix, ...

Setting a valid render target as active would take over canvasSettings from "current" to "new one" (so copying scale, matrix, ...). Set to null would then unset settings again - similar to what we discussed in the "restructuring"-issue.

While this introduces a big necessary change to the brl-module it would allow for a better "hooking in" to the core mechanics.

For now it looks inconsistent to allow `SetColor()` or `SetOrigin()` (did not test that yet) but require a `rendertarget.SetViewport()`.

**Comment by davecamp** [comment]
To be fair the Max2D graphics framework wasn't designed to be expanded or at least if it was then it wasn't very well designed for it. Many times I've thought about tweaking things to make it extendable but once you start you quickly realise that the whole thing needs tearing down and rewriting from scratch.

I agree it looks inconsistent, and I'm not so happy with it either.

**Comment by GWRon** [comment]
Before I forget to mention it: thanks for your commits as they help regardless of the underlaying issues.

**Comment by GWRon** [comment]
Hmm, I just recognized that some of my framework code relies on the ability to call "SetViewport()".

So when using this code together with your Render2Texture things get borked as the framework is not aware of a potential render2texture code (and it never should need to know that it is rendering to a texture - or not).

Any idea to temporarily override SetViewport to use whatever real function is used?
I think of something like

```Blitzmax
global _setViewportCallback(x:int,y:int,w:int,h:int)

_setViewportCallback = _defaultSetViewPort

Function _defaultSetViewport(...)
...
End Function

Function SetViewport(...)
 _setViewportCallback(x,y,w,h)
End Function
```

That way render2texture could backup the current callback when setting a renderimage as target (and setting its own setViewPort as the callback). when "nulling" the target again then the original callback is restored.


Or is this a bit "whacky-hacky" ?

**Comment by GWRon** [comment]
An even better approach would be - of course - to add the r2t code into brl.Max2D and the drivers - but this is surely a bit of a bigger task.

**Comment by GWRon** [comment]
For now I added to max2d.bmx
```Blitzmax
Global _setViewPortFunctionHook(x:int,y:int,w:int,h:int) = _defaultSetViewport
Global _max2DViewPortFunctionHook(x:int,y:int,w:int,h:int) = _defaultSetViewport

private
....
```
and replaced the SetViewPort()-function there with:
```BlitzMax
Function SetViewport( x,y,width,height )
	_setViewPortFunctionHook(x,y,width,height)
End Function

Function _defaultSetViewport( x,y,width,height )
	gc.viewport_x=x
	gc.viewport_y=y
	gc.viewport_w=width
	gc.viewport_h=height
	'round coordinates "correctly" to avoid values like 49.9997 to get rounded down
	'as the old floor() did
	Local x0=int( x / gc.vres_mousexscale  +0.5 )
	Local y0=int( y / gc.vres_mouseyscale  +0.5 )
	Local x1=int( (x+width) / gc.vres_mousexscale  +0.5 )
	Local y1=int( (y+height) / gc.vres_mouseyscale  +0.5 )
	_max2dDriver.SetViewport x0,y0,(x1-x0),(y1-y0)
End Function
```


In my code I have this now:
```BlitzMax
Function renderImageSetViewPort(x:int,y:int,w:int,h:int)
	'run original too
	_max2DViewPortFunctionHook(x,y,w,h)
	renderImage.SetViewPort(x,y,w,h)
End Function

...

	SetRenderImage(renderImage)
	_setViewPortFunctionHook = renderImageSetViewPort
		cls
		Level.Render()
	_setViewPortFunctionHook = _max2DViewPortFunctionHook
	SetRenderImage(Null)
...
```
As I also change the original viewport any "getViewport()" should work then for my framework as "before". No "backup/restore" of viewports for now.

**Comment by davecamp** [comment]
Hiya,

That sounds like a feasible workaround for the time being.

I agree it would be nice to put all of the r2t code into the main Max2D module(s). It would also help clean up the r2t code too due to some already existing workarounds that are needed to get at some of the Max2D 'cached' state.
