### ISSUE TITLE
R2T borks virtual resolution

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#5]
When using the r2t code with a SetVirtualResolution() "active" it borks up this setup when unbinding the texture again.

(non-working sample ):
```BlitzMax
SetVirtualResolution( 1920, 1080)
[...]
	local renderImage:TRenderImage = CreateRenderImage(graphicsContext, 100, 100)
	SetRenderImage(renderImage)
[...]
	SetRenderImage(Null)

	'currently needed: reset now borked up virtual resolution information (r2t is not
	'aware of it)
	SetVirtualResolution( 1920, 1080 )
```

Without the "second set" SetVirtualResolution():

![r2tbug_1](https://user-images.githubusercontent.com/2625226/31880800-e6a616a2-b7e1-11e7-9771-930dd793f402.jpg)

And this time with the call:
![r2tbug_2](https://user-images.githubusercontent.com/2625226/31880809-ed2c799e-b7e1-11e7-8c00-b973e77cd8c7.jpg)

**Comment by davecamp** [comment]
Hiya,
I'm using the following code. This doesn't show the error. Could you adjust it to show the error please...

    Local gc:TGraphics = Graphics(800, 600)
    SetVirtualResolution(1920, 1080)
    Local rt:TRenderImage = CreateRenderImage(gc, 300, 300)
    SetRenderImage(rt)

    ' render into the texture
    For Local i :Int = 0 To 100
    	SetColor Rand(0,255), Rand(0,255), Rand(0,255)
    	DrawText("Hey", Rand(0, rt.width-50), Rand(0, rt.height-20))
    Next

    SetRenderImage(Null)
    While Not KeyDown(KEY_ESCAPE)	
    	DrawImage(rt, 250, 250)
    	
    	DrawText("Virtual resolution", 50, 35)
    	DrawText("Testing", 50, 50)
    	Flip
    Wend

**Comment by GWRon** [comment]
Try this:

```BlitzMax
SuperStrict
'or path to your module...
Import "source/external/Render2Texture/renderimage.bmx"

Global gc:TGraphics = Graphics(800, 600)
SetVirtualResolution(1920, 1080)

Global renderImage:TRenderImage
Global setVirtualResolutionAgain:Int = False
Global lastChange:Int = MilliSecs()


Global bg:TImage = CreateImage(1920, 1080)
'create a checkerboard
Global pix:TPixmap = LockImage(bg)
Local cols:Int[] = [(Int(255 * $1000000) + Int(255 * $10000) + Int(255 * $100) + Int(255)), ..
                  (Int(255 * $1000000) + Int(255 * $10000) + Int(0 * $100) + Int(0))]
For Local x:Int = 0 Until 1920
	For Local y:Int = 0 Until 1080
		WritePixel(pix, x,y, cols[ ((Floor(x / 80) Mod 2 = 0) + (Floor(y / 80) Mod 2 = 0)) Mod 2 ])
	Next
Next

	


Function CreateRTImage:TRenderImage()
	Local rt:TRenderImage = CreateRenderImage(gc, 300, 300)
	SetRenderImage(rt)
	' render into the texture
	For Local i :Int = 0 To 100
		SetColor Rand(0,255), Rand(0,255), Rand(0,255)
		DrawText("Hey", Rand(0, rt.width-50), Rand(0, rt.height-20))
	Next

	SetRenderImage(Null)

	If setVirtualResolutionAgain Then SetVirtualResolution(1920, 1080)

	Return rt
End Function


While Not KeyDown(KEY_ESCAPE)	
	Cls
	
	SetColor 255,255,255
	If bg Then DrawImage(bg, 0, 0)
	
	If Not renderImage Then renderImage = CreateRTImage()
	If MilliSecs() - lastChange > 200
		renderImage = CreateRTImage()
		setVirtualResolutionAgain = 1 - setVirtualResolutionAgain
		lastChange = MilliSecs() + 200
	EndIf

	DrawImage(renderImage, 250, 250)
	
	DrawText("Virtual resolution", 50, 35)
	DrawText("Testing", 50, 50)
	Flip
Wend
```

Output (on my linux box):
![r2t](https://user-images.githubusercontent.com/2625226/31906210-ced0cf28-b830-11e7-93f8-e520a8bc1c68.gif)


The stretched quads are when using setVirtualResolution after Render2Image is used, the unstretched one is without...

**Comment by davecamp** [comment]
Thankyou for the example!
Should be ok now.

**Comment by davecamp** [comment]
I'm not sure if you did it just for the example but creating resources during the 'hot-loop' is generally not a good idea.

**Comment by davecamp** [comment]
Still there on GL, sorry, my bad

**Comment by davecamp** [comment]
Should be ok this time.

**Comment by GWRon** [comment]
I want to "cache" images.

So instead of eg. drawing 6 "scaled down" sprites each time, I would render them into a cache image and just draw that then.


In generally a "render 2 texture" should be "realtime-capable" (like rendering a game to one side of a 3d cube).

**Comment by GWRon** [comment]
PS: Current revision works. Thanks for the fast fix.

**Comment by davecamp** [comment]
Indeed. You're correct, rendering to a texture is a real time process.
Unless I've misunderstood what you're doing in the main app...
Creating those resources during the main loop could result in performance issues.
By all means create the render textures up front before the main loop then you pick and choose which one to render to in real time - doing that would not raise any performance concerns :+1:

**Comment by GWRon** [comment]
I just did it so you "see" it. In my real app I just create them "on request" (eg. if an item is taken out of the bag).

**Comment by davecamp** [comment]
Ahh I see. I did hope that you did it just for the test example :-)
Thanks again for the example and raising the issue.
