### ISSUE TITLE
No correct method to destroy a render image

### ISSUE THREAD

**Issue by davecamp** [davecamp/Render2Texture#6]
There needs to be a function such as DestroyRenderImage to correctly free up all resources when a render image is not needed any more.

**Comment by GWRon** [comment]
If the resources are not maintained by the GC - shouldn't the `Delete()` method of the type be called when nothing is referencing the image any longer? Then in `Delete()` cleanup could take place

**Comment by davecamp** [comment]
That would normally happen yes, and still does. except there is a reference to each renderimage in a TList.

There are a couple of reasons for this... 
1. the main reason is immediacy. I want users to know that any gpu resources are destroyed 'at a known time' as opposed to 'at some time in the future'.
For example when switching a rendering Api from OpenGL to DirectX etc If there are many gpu resources that aren't freed pronto then it *may* cause temporary gpu out of memory issues and hidden difficult to find bugs. Prevention is better than cure in that situation.
2. d3d9 needs resources to survive a 'device reset' cycle, Having them stored in a list relieves you of the burden of tracking those resources yourself in order to destroy and recreate them during that cycle. I take care of that in the code for you .
