### ISSUE TITLE
Some Imports missing

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#7]
Sorry, it is easier now to write this in an issue than creating a PR:

glrenderimage.bmx:
```BlitzMax
Strict
Import Pub.glew
Import Brl.GLMax2D
```

renderimageinterface.bmx
```BlitzMax
Strict
Import Brl.Max2D
```

There might be others missing too - just use a "framework Brl.StandardIO" in your sample code and check what is missing.

**Comment by davecamp** [comment]
Thanks for the heads up!
