### ISSUE TITLE
SetColor during render2texture affects outside color

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#8]
When changing the color within a set render texture target, this affects the color used when rendering to the screen.
(to see it just use the example provided in the last issue - and remove the `SetColor 255,255,255`)

I am not sure whether it is a "bug" in the right sense. I just assumed that a render target has its own "setup" Or is the current behaviour the "expected" one?

Happens for rotation/scale too.

If this is intented then of course I need to "backup" all transformations when creating cache-images using r2t and afterwards "restore" all transformations.

Hmm, maybe it would be a good Idea to have 2 helpers then? "rt.backupTransformation()" and "rt.RestoreTransformation()" (or whatever you name things containing rotation, scale, color, [handle?]).

**Comment by davecamp** [comment]
That's quite expected.
Max2D works as a state machine. Anything that sets state such as SetScale, SetColor, SetAlpha, SetRotation, SetRenderImage, will change just that state and everything else will remain the same.

If you need to rewind state if may be better to create a 'state stack' to push and pop state as required?

**Comment by davecamp** [comment]
Or maybe create a snapshot of all states, do the work required, then revert back to the state that was recorded in the snapshot?

**Comment by GWRon** [comment]
Ok so it is expected behaviour. Just wanted to know that.
