### ISSUE TITLE
Rendered Textures are upside down

### ISSUE THREAD

**Issue by GWRon** [davecamp/Render2Texture#9]
Somehow (after an NVIDIA-driver update on my linux machine) the created r2t-textures are upside down:

example1.bmx
![upsidedown](https://user-images.githubusercontent.com/2625226/32148998-a85c9f16-bcfe-11e7-93ae-f383e8702ffe.png)

**Comment by GWRon** [comment]
Within my VirtualBox I cannot run the example as it only supports OGL in the virtual XP machine. I removed the occourences of DX in the module - and made the example using a `Framework Brl.GLMax2D` (to avoid loading of dx9 stuff - leading to crashes).

It then crashes in `glrenderimage.bmx: CreateRenderTarget()` `glGenFramebuffers(1,Varptr _fbo)`. Seems VirtualBox is not capable of FBOs there.


But still on my normal PC the image is "upside down" - nothing I intend to have that way.

**Comment by GWRon** [comment]
Ok, Reverting to the version _before_ fixing the virtual-resolution-stuff made the example work again as intended... 

So I somehow think you introduced a new bug :p

**Comment by GWRon** [comment]
I replaced the newly introduced matrix:

from
```BlitzMax
		_matrix = [	2.0/width, 0.0, 0.0, 0.0,..
					0.0, -2.0/height, 0.0, 0.0,..
					0.0, 0.0, 1.0, 0.0,..
					-1-(1.0/width), 1+(1.0/height), 1.0, 1.0 ]
```
to
```blitzmax
		_matrix = [	2.0/width, 0.0, 0.0, 0.0,..		'left (x-axis)
					0.0, 2.0/height, 0.0, 0.0,..	'top (y-axis)
					0.0, 0.0, 1.0, 0.0,..			'z-axis
					-1-(1.0/width), -1-(1.0/height), 1.0, 1.0 ] '-translation
```

y-axis becomes a negative value and second translation value gets negated too.


Now it works again.

**Comment by davecamp** [comment]
Oops, sorry about that!
I'm not sure what happened there but thankyou for raising the issue!
